### ISSUE TITLE
What's the best way to layout help requests list in code

### ISSUE THREAD

**Issue by tm-kn** [tjm3/helpme-android#7]
We need to have a good technical solution to layout the list of requests in code. Need research.

**Comment by tm-kn** [comment]
@jurkonism Could you help him, please?
@Mamadu12 Do you have any troubles with this task?

**Comment by Mamadu12** [comment]
[requestLayout example.txt](https://github.com/tjm3/helpme-android/files/177666/requestLayout.example.txt)

**Comment by tm-kn** [comment]
Okay. Any screenshot? How to we add items to the list in Java?

**Comment by tm-kn** [comment]
The issue has been dealt with in 86d0937735f86517eced7cc44fc3f598f625fee5. I'm not happy that you haven't provided a full solution and therefore I had to do research instead of you. For the future reference, the solution is.

``` XML
<ListView
        android:id="@+id/help_requests_list_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"></ListView>
```

``` Java
private ArrayList<String> helpRequestsList;
private ArrayAdapter<String> helpRequestListAdapter;
private ListView helpRequestsListView;

this.helpRequestsList = new ArrayList<String>();
this.helpRequestListAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, this.helpRequestsList);
this.helpRequestsListView = (ListView) findViewById(R.id.help_requests_list_view);
helpRequestsListView.setAdapter(this.helpRequestListAdapter);

this.helpRequestsList.add("some random request");
// Important to run "notifyDataSetChanged()" after every update to the list to reflect all the changes
this.helpRequestListAdapter.notifyDataSetChanged();

```

To register clicks on the list I used `ListView.setOnItemClickListener()`.
